Tiny fix
kusumotolab/kJuiceApp pull request #51
Opened 2023-05-02 08:18 UTC by h-takesg

気になったことを少しだけ

* `Backend.ts`の`recall()`で使うHTTPメソッドを修正（正：`DELETE`，誤：`GET`）
* Homeの商品カード群が画面幅より長くなると右側全体がスクロールしていたので商品カードだけスクロールするように変更

before
![image](https://user-images.githubusercontent.com/82633007/235615184-34c2a474-b922-4b34-8a32-0510d9c625c3.png)

after
![image](https://user-images.githubusercontent.com/82633007/235615289-075c4db6-04e8-4c9d-aaa0-9d5e80e0a59e.png)

2023-05-03 10:19 UTC, grtw2116 requested changes

2023-05-03 10:19 UTC, grtw2116 commented on frontend/src/HomePage/Item/Food/FoodPane.tsx
> +      <Flex padding="5px" overflowX="auto" gap={4}>
```suggestion
      <Flex p={1} overflowX="auto" gap={4}>
```

Chakra UIでは[スペース幅がテーマレベルで決められている](https://chakra-ui.com/docs/styled-system/theme#spacing)ので，そちらの使用をお願いします
ただし，値が`5px`でないとダメな場合は変更しなくて大丈夫です

2023-05-03 10:19 UTC, grtw2116 commented on frontend/src/HomePage/Item/Juice/JuicePane.tsx
同上です

2023-05-03 10:21 UTC, grtw2116 requested changes

2023-05-03 10:21 UTC, grtw2116 commented on frontend/src/HomePage/Item/Juice/JuicePane.tsx
> +      <Flex padding="5px" overflowX="auto" gap={4}>
```suggestion
      <Flex p={1} overflowX="auto" gap={4}>
```
同上です

2023-05-04 15:47 UTC, h-takesg commented
thx
paddingの意図を共有しておくと，overflowを指定すると（なぜか？）商品カードの影が切れて表示されるのでflexの内側に余白を入れています

2023-05-05 10:34 UTC, grtw2116 approved these changes
LGTM

2023-05-05 11:18 UTC, merged