商品の画像をユーザが自由に設定できるようにした．
kusumotolab/kJuiceApp pull request #63
Opened 2023-05-20 15:27 UTC by Haur514

2023-05-31 09:42 UTC, Haur514 commented
修正中

2023-06-03 09:40 UTC, Haur514 commented
reviewお願いします

2023-06-20 07:08 UTC, kusumoto-lab commented on frontend/src/util/Backend.ts
> +        if (res.status === 200) return res.data;
204を特例として弾いた方がよさそう
読みやすくなる

2023-06-20 07:08 UTC, kusumoto-lab commented on frontend/src/util/Backend.ts
> +        if (res.status === 200) return res.data;
Memberも

2023-10-18 13:46 UTC, grtw2116 requested changes
LGTMです．

一点だけ，商品一覧の取得処理をカスタムフック`useItems()`を使った実装にしてもらえませんか．この点だけよろしくお願いします．

2023-10-18 13:46 UTC, grtw2116 commented on frontend/src/Setting/Admin/ItemIconChange/ItemIconChangePane.tsx
> +  }, []);
```suggestion
```

2023-10-18 13:46 UTC, grtw2116 commented on frontend/src/Setting/Admin/ItemIconChange/ItemIconChangePane.tsx
> +            {itemList.map(({ id, name }) => {
```suggestion
            {items.map(({ id, name }) => {
```

2023-10-30 05:42 UTC, grtw2116 reviewed
types.tsからLogoDictionaryを削除お願いします

2023-10-31 10:34 UTC, grtw2116 approved these changes

2023-10-31 10:34 UTC, merged